# ICA 3

## Problem 1

In [1]:
import numpy as np

In [2]:
new_array = np.linspace(11, 42, 100)
new_array

array([11.        , 11.31313131, 11.62626263, 11.93939394, 12.25252525,
       12.56565657, 12.87878788, 13.19191919, 13.50505051, 13.81818182,
       14.13131313, 14.44444444, 14.75757576, 15.07070707, 15.38383838,
       15.6969697 , 16.01010101, 16.32323232, 16.63636364, 16.94949495,
       17.26262626, 17.57575758, 17.88888889, 18.2020202 , 18.51515152,
       18.82828283, 19.14141414, 19.45454545, 19.76767677, 20.08080808,
       20.39393939, 20.70707071, 21.02020202, 21.33333333, 21.64646465,
       21.95959596, 22.27272727, 22.58585859, 22.8989899 , 23.21212121,
       23.52525253, 23.83838384, 24.15151515, 24.46464646, 24.77777778,
       25.09090909, 25.4040404 , 25.71717172, 26.03030303, 26.34343434,
       26.65656566, 26.96969697, 27.28282828, 27.5959596 , 27.90909091,
       28.22222222, 28.53535354, 28.84848485, 29.16161616, 29.47474747,
       29.78787879, 30.1010101 , 30.41414141, 30.72727273, 31.04040404,
       31.35353535, 31.66666667, 31.97979798, 32.29292929, 32.60

In [3]:
reshaped_array = new_array.reshape((5, -1))
reshaped_array

array([[11.        , 11.31313131, 11.62626263, 11.93939394, 12.25252525,
        12.56565657, 12.87878788, 13.19191919, 13.50505051, 13.81818182,
        14.13131313, 14.44444444, 14.75757576, 15.07070707, 15.38383838,
        15.6969697 , 16.01010101, 16.32323232, 16.63636364, 16.94949495],
       [17.26262626, 17.57575758, 17.88888889, 18.2020202 , 18.51515152,
        18.82828283, 19.14141414, 19.45454545, 19.76767677, 20.08080808,
        20.39393939, 20.70707071, 21.02020202, 21.33333333, 21.64646465,
        21.95959596, 22.27272727, 22.58585859, 22.8989899 , 23.21212121],
       [23.52525253, 23.83838384, 24.15151515, 24.46464646, 24.77777778,
        25.09090909, 25.4040404 , 25.71717172, 26.03030303, 26.34343434,
        26.65656566, 26.96969697, 27.28282828, 27.5959596 , 27.90909091,
        28.22222222, 28.53535354, 28.84848485, 29.16161616, 29.47474747],
       [29.78787879, 30.1010101 , 30.41414141, 30.72727273, 31.04040404,
        31.35353535, 31.66666667, 31.97979798, 3

In [4]:
# memory when array is a float
reshaped_array.nbytes

800

In [5]:
int_array = reshaped_array.astype(int)
int_array.reshape(5, -1)
int_array

array([[11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15,
        16, 16, 16, 16],
       [17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21,
        22, 22, 22, 23],
       [23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 28,
        28, 28, 29, 29],
       [29, 30, 30, 30, 31, 31, 31, 31, 32, 32, 32, 33, 33, 33, 34, 34,
        34, 35, 35, 35],
       [36, 36, 36, 36, 37, 37, 37, 38, 38, 38, 39, 39, 39, 40, 40, 40,
        41, 41, 41, 42]])

In [6]:
np.int8(reshaped_array)

array([[11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15,
        16, 16, 16, 16],
       [17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21,
        22, 22, 22, 23],
       [23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 28,
        28, 28, 29, 29],
       [29, 30, 30, 30, 31, 31, 31, 31, 32, 32, 32, 33, 33, 33, 34, 34,
        34, 35, 35, 35],
       [36, 36, 36, 36, 37, 37, 37, 38, 38, 38, 39, 39, 39, 40, 40, 40,
        41, 41, 41, 42]], dtype=int8)

In [7]:
# memory when array is an int
int_array.nbytes

800

## Problem 2

In [9]:
x = np.array([[0., 1., 3., 0., 5., 5.],
              [0., 0., 3., 0., 0., 0.],
              [0., 2., 3., 0., 0., 0.],
              [0., 0., 3., 4., 4., 4.],
              [0., 0., 3., 4., 4., 4.],
              [0., 0., 3., 4., 4., 4.]])

In [10]:
# get 1

x[0, 1]

1.0

In [16]:
# get 2

x[2, 1]

2.0

In [17]:
# get 3

x[:, 2]

array([3., 3., 3., 3., 3., 3.])

In [18]:
# get 4

x[3:, 3:]

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [19]:
# get 5

x[0, -2:]

array([5., 5.])

In [20]:
# last column

x[:, 5]

array([5., 0., 0., 4., 4., 4.])

In [21]:
# last row

x[5, :]

array([0., 0., 3., 4., 4., 4.])

In [22]:
# first three elements of last column of x

x[:3, 5]

array([5., 0., 0.])

## Problem 3

In [25]:
# grades array
# rows are each student
# columns are each quiz
grades_array = np.array([[56, 77, 94], [99, 89, 95], [34, 42, 51], [100, 100, 100], [76, 78, 79]])
grades_array

array([[ 56,  77,  94],
       [ 99,  89,  95],
       [ 34,  42,  51],
       [100, 100, 100],
       [ 76,  78,  79]])

In [34]:
# mean among all students and quizzes
grades_array.mean()

78.0

In [26]:
# mean score for each student
grades_array.mean(axis=1)

array([ 75.66666667,  94.33333333,  42.33333333, 100.        ,
        77.66666667])

In [27]:
# mean score among the quizzes
grades_array.mean(axis=0)

array([73. , 77.2, 83.8])

In [32]:
# mean of student who had the highest mean
max(grades_array.mean(axis=1))

100.0

In [39]:
# quiz with lowest mean score
grades_array.mean(axis=0).argmin()

0